spring.application.name=Parkify
server.port=8080

logging.level.org.springframework.security=DEBUG
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yasith.hasarinda2003@gmail.com
spring.mail.password=yyac mpim xjrs rmvj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Stripe Configuration
stripe.api.key=${STRIPE_API_KEY:sk_test_placeholder}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:whsec_placeholder}
stripe.redirect.url=http://localhost:3000

# Twilio SMS Configuration
twilio.account.sid=${TWILIO_ACCOUNT_SID:AC_placeholder}
twilio.auth.token=${TWILIO_AUTH_TOKEN:placeholder}
twilio.phone.number=+94776945474

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://hase_db:Hase2324@ac-9e68srw-shard-00-00.whf5hiq.mongodb.net:27017,ac-9e68srw-shard-00-01.whf5hiq.mongodb.net:27017,ac-9e68srw-shard-00-02.whf5hiq.mongodb.net:27017/?ssl=true&replicaSet=atlas-fjlyo9-shard-0&authSource=admin&appName=Cluster0
spring.data.mongodb.database=parkify_db
